
# This file is automatically generated during the generation of setup.py
# Copyright 2023, Engineconomics
author = "Santiago Giraldo"
author_email = "sgmlmail@protonmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '85e6d532a2e3d9c226be669296d8c81719fb35f3'
release = False
contributors = ['Santiago Giraldo <@tiagogiraldo>', '']
homepage = "https://github.com/tiagogiraldo/engineconomics"
