
# This file is automatically generated during the generation of setup.py
# Copyright 2023, Engineconomics
author = "Santiago Giraldo"
author_email = "sgmlmail@protonmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = 'cfc8180ae20612cc5700669b29ed62294a1bce90'
release = False
contributors = ['Santiago Giraldo <@tiagogiraldo>', '']
homepage = "https://github.com/tiagogiraldo/engineconomics"
