
# This file is automatically generated during the generation of setup.py
# Copyright 2023, Engineconomics
author = "Santiago Giraldo"
author_email = "sgmlmail@protonmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '60904e22bf4a4838d6c53da8c51e6ce4d61bc7bb'
release = False
contributors = ['Santiago Giraldo <@tiagogiraldo>', '']
homepage = "https://github.com/tiagogiraldo/engineconomics"
